/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.0-7-g4f8b3891ee-20250914"
#endif /* AVUTIL_FFVERSION_H */
